module Breakout
  WINDOW_SIZE_X = 800
  WINDOW_SIZE_Y = 500
  BLOCK_SIZE_X  = 100
  BLOCK_SIZE_Y  =  30
  BLOCK_COUNT_X =   6
  BLOCK_COUNT_Y =   5
  PLAYER_SIZE_X = 150
  PLAYER_SIZE_Y =  20
  PLAYER_SPEED  = 400
  MARGIN_SIDE   = (WINDOW_SIZE_X - BLOCK_SIZE_X * BLOCK_COUNT_X) / 2
  MARGIN_TOP    =  40
  MARGIN_BOTTOM =  20
  BALL_SIZE     =  10
  BALL_VELOCITY = 300
end
